dependencies:
  - conda-forge::arpack
  - conda-forge::lapack
  - pip
  - python=3.8
  - pip:
      - setuptools==59.5.0
      - umap-learn
      - scipion-em
      - tqdm==4.64.0
      - protobuf==3.20.3
