# **************************************************************************
# * Author:  Remi Vuillemot
# * IMPMC, UPMC Sorbonne University
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# **************************************************************************

import joblib
from pyworkflow.protocol.params import (PointerParam, EnumParam, IntParam)
from pwem.protocols import ProtAnalysis3D
from pyworkflow.utils.path import makePath, copyFile
from pyworkflow.protocol import params
from pwem.emlib import MetaData, MDL_ENABLED, MDL_NMA_MODEFILE,MDL_ORDER
from pwem.objects import SetOfNormalModes, AtomStruct
from .convert import rowToMode
from xmipp3.base import XmippMdRow
from continuousflex.protocols.utilities.genesis_utilities import numpyArr2dcd,dcd2numpyArr

import numpy as np
import glob
from sklearn import decomposition
from joblib import dump

from .utilities.pdb_handler import ContinuousFlexPDBHandler
import continuousflex
from continuousflex import Plugin
from subprocess import check_call
import sys

PDB_SOURCE_SUBTOMO = 0
PDB_SOURCE_PATTERN = 1
PDB_SOURCE_OBJECT = 2
PDB_SOURCE_TRAJECT = 3
PDB_SOURCE_ALIGNED = 4

REDUCE_METHOD_PCA = 0
REDUCE_METHOD_UMAP = 1


class FlexProtDimredPdb(ProtAnalysis3D):
    """
    Applies dimensionality reduction to collections of macromolecular structures represented as PDB files or molecular dynamics trajectories. The protocol transforms large ensembles of structural conformations into a compact low-dimensional representation that facilitates visualization, interpretation, and exploration of conformational variability.

    AI Generated:

    PDB Dimensionality Reduction (FlexProtDimredPdb) - User Manual
        Overview

        The PDB Dimensionality Reduction protocol is designed to analyze structural heterogeneity in
        ensembles of macromolecular conformations. Its primary goal is to transform a large collection
        of atomic structures into a reduced coordinate space where the major patterns of structural
        variability can be observed and interpreted more easily. This approach is particularly useful
        when studying flexible proteins, molecular machines, conformational transitions, or molecular
        dynamics simulations that generate thousands of structural snapshots.

        Instead of examining each structure individually, the protocol summarizes the ensemble into a
        small number of dimensions that capture the dominant motions and relationships among
        conformations. The resulting reduced space allows researchers to identify structural trends,
        clusters, transition pathways, and regions of conformational sampling that may otherwise be
        difficult to detect.

        Inputs and Supported Data Sources

        The protocol accepts structural information from several sources. Users may analyze PDB files
        generated during subtomogram synthesis workflows, collections of PDB files stored on disk,
        Scipion sets of atomic structures, molecular dynamics trajectories, or outputs generated by
        dedicated PDB alignment workflows.

        This flexibility allows the protocol to be used in a wide variety of structural biology
        applications. Experimental conformational ensembles, computational simulations, integrative
        modeling results, and synthetic benchmark datasets can all be projected into a common reduced
        representation for comparative analysis.

        When working with trajectory data, it is possible to analyze only a selected region of the
        trajectory. This enables users to focus on equilibrated states, specific simulation intervals,
        or representative subsets of very large simulations while reducing computational requirements.

        Dimensionality Reduction Strategies

        The protocol provides multiple approaches for reducing structural dimensionality. Each method
        emphasizes different aspects of conformational variability and may be more appropriate depending
        on the biological question being investigated.

        Principal Component Analysis is particularly useful when the dominant motions can be reasonably
        described by linear combinations of atomic displacements. In many structural biology studies,
        principal components correspond to biologically meaningful collective motions such as domain
        rearrangements, hinge movements, opening and closing events, or large-scale flexibility.

        UMAP offers a nonlinear alternative that is often advantageous when conformational landscapes
        contain complex geometries, branching pathways, or multiple separated states. This approach can
        reveal relationships between structures that may not be captured by purely linear methods and
        is frequently used to explore heterogeneous ensembles with rich conformational diversity.

        Structural Similarity and Distance Interpretation

        The reduced coordinates should be interpreted as a representation of structural relationships
        rather than direct physical coordinates. Structures located close together in the reduced space
        generally correspond to similar conformations, while structures positioned farther apart tend
        to represent larger structural differences.

        In many applications, clusters observed within the reduced space correspond to metastable
        conformational states, functional substates, or structurally related populations. Continuous
        trajectories through the reduced space may indicate gradual conformational transitions or
        dynamic pathways sampled during molecular motion.

        Selection of Dimensionality

        The number of dimensions retained in the reduced representation determines how much structural
        variability can be preserved. A small number of dimensions is often sufficient for visualization
        and exploratory analysis, whereas larger dimensionalities may be preferable when capturing more
        subtle motions or preparing data for downstream computational processing.

        Choosing too few dimensions may oversimplify the conformational landscape and hide meaningful
        structural features. Conversely, selecting too many dimensions may preserve noise and reduce the
        interpretability of the results. The optimal choice depends on the complexity of the molecular
        system and the scientific objectives of the study.

        Principal Components and Collective Motions

        When Principal Component Analysis is used, the protocol additionally produces a mean structure
        and a set of collective motion vectors describing the dominant directions of structural
        variability within the ensemble. These motions can be interpreted as large-scale conformational
        trends that summarize how atomic coordinates vary across the dataset.

        Such collective modes are valuable for understanding flexibility, identifying functional
        motions, and generating simplified representations of structural dynamics. They can also serve
        as inputs for subsequent analyses focused on conformational exploration and modeling.

        Practical Recommendations

        For many structural biology applications, Principal Component Analysis provides an excellent
        starting point because its results are easy to interpret and often correspond directly to
        biologically meaningful motions. It is particularly useful when studying continuous conformational
        changes and dominant collective movements.

        UMAP is often advantageous when exploring highly heterogeneous datasets, large molecular
        dynamics simulations, or systems expected to contain multiple conformational basins. In these
        situations, nonlinear embeddings may reveal relationships that are difficult to observe using
        linear approaches alone.

        Regardless of the chosen method, careful inspection of the reduced space is recommended.
        Biological interpretation should always be supported by examination of representative
        structures from different regions of the embedding to ensure that observed patterns correspond
        to meaningful conformational differences.

        Outputs and Interpretation

        The protocol generates a reduced coordinate matrix describing the position of every analyzed
        structure within the reduced conformational space. Depending on the selected method, additional
        information describing dominant structural motions may also be produced.

        These outputs provide a compact and interpretable representation of structural variability that
        can be used for visualization, clustering, classification, conformational landscape analysis,
        trajectory exploration, and integration with downstream flexible modeling workflows.

        Final Perspective

        For researchers studying molecular flexibility, dimensionality reduction serves as a bridge
        between high-dimensional atomic coordinates and biologically interpretable conformational
        landscapes. By condensing complex structural ensembles into a manageable representation, the
        protocol enables efficient exploration of molecular motion, facilitates hypothesis generation,
        and helps reveal the fundamental patterns governing structural variability.
    """
    _label = 'pdb dimentionality reduction'


    # --------------------------- DEFINE param functions --------------------------------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam('pdbSource', EnumParam, default=PDB_SOURCE_SUBTOMO,
                      label='Source of PDBs',
                      choices=['Used for subtomogram synthesis', 'File pattern', 'Object', 'Trajectory Files', 'Align PDBs protocol'],
                      help='Use the file pattern as file location with /*.pdb')
        form.addParam('pdbs', params.PointerParam, pointerClass='FlexProtSynthesizeSubtomo',
                      condition='pdbSource ==  %i'%PDB_SOURCE_SUBTOMO,
                      label="Subtomogram synthesis",
                      help='Point to a protocol of synthesizing subtomograms, the ground truth PDBs will be used as input')
        form.addParam('pdbs_file', params.PathParam,
                      condition='pdbSource == %i' % PDB_SOURCE_PATTERN,
                      label="List of PDBs",
                      help='Use the file pattern as file location with /*.pdb')
        form.addParam('setOfPDBs', params.PointerParam, pointerClass='SetOfPDBs, SetOfAtomStructs',
                      condition='pdbSource == %i' % PDB_SOURCE_OBJECT,
                      label="Set of PDBs",
                      help='Use a scipion object SetOfPDBs / SetOfAtomStructs')
        form.addParam('dcds_file', params.PathParam,
                      condition='pdbSource == %i' % PDB_SOURCE_TRAJECT,
                      label="DCD trajectory file (s)",
                      help='Use the file pattern as file location with /*.dcd')
        form.addParam('dcd_ref_pdb', params.PointerParam, pointerClass='AtomStruct',
                      condition='pdbSource == %i' % PDB_SOURCE_TRAJECT,
                      label="trajectory Reference PDB",
                      help='Reference PDB of the trajectory (Only used for structural information (Atom name, residue number etc)'
                           '. The coordinates inside this PDB are not used. The atoms number and position in the file must'
                           ' correspond to the DCD file. ')
        form.addParam('dcd_start', params.IntParam, default=0,
                      condition='pdbSource == %i' % PDB_SOURCE_TRAJECT,
                      label="Beginning of the trajectory",
                      help='Index of the desired begining of the trajectory', expertLevel=params.LEVEL_ADVANCED)
        form.addParam('dcd_end', params.IntParam, default=-1,
                      condition='pdbSource == %i' % PDB_SOURCE_TRAJECT,
                      label="Ending of the trajectory",
                      help='Index of the desired end of the trajectory', expertLevel=params.LEVEL_ADVANCED)
        form.addParam('dcd_step', params.IntParam, default=1,
                      condition='pdbSource == %i' % PDB_SOURCE_TRAJECT,
                      label="Step of the trajectory",
                      help='Step to skip points in the trajectory', expertLevel=params.LEVEL_ADVANCED)

        form.addParam('alignPdbProt', params.PointerParam, pointerClass='FlexProtAlignPdb',
                      condition='pdbSource == %i' % PDB_SOURCE_ALIGNED,
                      label="Align PDBs Protocol",
                      help='Point to a protocol of pdb aligned. For large data set, you can use here the align pdb protocol as input '
                           'and avoid creating an output set of pdb in the align pdb protocol.')

        form.addParam('loadReducedSpace', params.BooleanParam, label="Load an existing reduced space ?",
                      default=False,help="Skip the analysis and load the pre existing reduced space", expertLevel=params.LEVEL_ADVANCED)

        form.addParam('reducedSpace', params.PathParam, label="Provide a txt file of the existing reduced space", condition="loadReducedSpace",
                    help="Cloud of point of N dimension constituing a reduced space "
                                         " obtained by any reduction method. The file is a txt file.", expertLevel=params.LEVEL_ADVANCED)

        form.addParam('method', params.EnumParam, label="Reduction method", default=REDUCE_METHOD_PCA,
                      choices=['PCA', 'UMAP'],help="")
        form.addParam('n_neigbors', params.IntParam, label="n_neigbors", condition="method==%i"%REDUCE_METHOD_UMAP,
                      default=15,help="", expertLevel=params.LEVEL_ADVANCED)
        form.addParam('n_epocks', params.IntParam, label="n_epocks", condition="method==%i"%REDUCE_METHOD_UMAP,
                      default=1000,help="", expertLevel=params.LEVEL_ADVANCED)
        form.addParam('metric_rmsd', params.BooleanParam, label="Use RMSD as metric ?", condition="method==%i"%REDUCE_METHOD_UMAP,
                      default=False,help="", expertLevel=params.LEVEL_ADVANCED)
        form.addParam('low_memory', params.BooleanParam, label="low_memory", condition="method==%i"%REDUCE_METHOD_UMAP,
                      default=False,help="", expertLevel=params.LEVEL_ADVANCED)
        form.addParam('reducedDim', IntParam, default=10,
                      label='Number of Principal Components')

        # --------------------------- INSERT steps functions --------------------------------------------
    def _insertAllSteps(self):
        self._insertFunctionStep('readInputFiles')
        self._insertFunctionStep('performDimred')
        if self.method.get() == REDUCE_METHOD_PCA:
            self._insertFunctionStep('createOutputStep')

    # --------------------------- STEPS functions --------------------------------------------
    def readInputFiles(self):
        inputFiles = self.getInputFiles()

        # Get pdbs coordinates
        if self.pdbSource.get() == PDB_SOURCE_TRAJECT:
            pdbs_arr = dcd2numpyArr(inputFiles[0])
            start = self.dcd_start.get()
            step = self.dcd_step.get()
            end = self.dcd_end.get() if self.dcd_end.get() != -1 else pdbs_arr.shape[0]
            pdbs_arr = pdbs_arr[start:end:step]
            for i in range(1,len(inputFiles)):
                pdb_arr_i = dcd2numpyArr(inputFiles[i])
                pdbs_arr = np.concatenate((pdbs_arr, pdb_arr_i[start:end:step]), axis=0)


        elif self.pdbSource.get() == PDB_SOURCE_ALIGNED:
            pdbs_arr = dcd2numpyArr(inputFiles[0])
        else:
            pdbs_matrix = []
            for pdbfn in inputFiles:
                try:
                    # Read PDBs
                    mol = ContinuousFlexPDBHandler(pdbfn)
                    pdbs_matrix.append(mol.coords)
                except RuntimeError:
                    print("Warning : Can not read PDB file %s " % pdbfn)
            pdbs_arr = np.array(pdbs_matrix)

        # save as dcd file
        numpyArr2dcd(pdbs_arr, self._getExtraPath("coords.dcd"))

    def performDimred(self):

        if self.loadReducedSpace.get():
            copyFile(self.reducedSpace.get(), self.getOutputMatrixFile())
            return

        pdbs_arr = dcd2numpyArr(self._getExtraPath("coords.dcd"))
        nframe, natom,_ = pdbs_arr.shape
        pdbs_matrix = pdbs_arr.reshape(nframe, natom*3)

        if self.method.get() == REDUCE_METHOD_PCA:
            pca = decomposition.PCA(n_components=self.reducedDim.get())
            Y = pca.fit_transform(pdbs_matrix)
            dump(pca, self._getExtraPath('pca_pickled.joblib'))

            pathPC = self._getPath("modes")
            pdb = ContinuousFlexPDBHandler(self.getPDBRef())
            pdb.coords = pca.mean_.reshape(pdbs_matrix.shape[1] // 3, 3)
            pdb.write_pdb(self._getPath("atoms.pdb"))
            makePath(pathPC)
            matrix = pca.components_.reshape(self.reducedDim.get(),pdbs_matrix.shape[1]//3,3)
            self.writePrincipalComponents(prefix=pathPC, matrix = matrix)
            np.savetxt(self.getOutputMatrixFile(),Y)

        elif self.method.get() == REDUCE_METHOD_UMAP:
            pdbs_dump = self._getTmpPath('pdbs_dump.pkl')
            joblib.dump(pdbs_matrix, pdbs_dump)
            args = "%d %d %d %s %s %s %i %i" % (self.reducedDim.get(), self.n_neigbors.get(), self.n_epocks.get(),
                                       pdbs_dump, self._getExtraPath('pca_pickled.joblib'), self.getOutputMatrixFile(), int(self.low_memory.get()),
                                                int(self.metric_rmsd.get()))
            script_path = continuousflex.__path__[0] + '/protocols/utilities/umap_run.py '
            command = "python " + script_path + args
            command = Plugin.getContinuousFlexCmd(command)
            check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
                       env=None, cwd=None)


    def createOutputStep(self):
            # Metadata
            mdOut = MetaData()
            for i in range(self.reducedDim.get()):
                objId = mdOut.addObject()
                modefile = self._getPath("modes", "vec.%d" % (i + 1))
                mdOut.setValue(MDL_NMA_MODEFILE, modefile, objId)
                mdOut.setValue(MDL_ORDER, i + 1, objId)
                mdOut.setValue(MDL_ENABLED, 1, objId)
            mdOut.write(self._getPath("modes.xmd"))

            # Sqlite object
            pcSet =SetOfNormalModes(filename=self._getPath("modes.sqlite"))
            row = XmippMdRow()
            for objId in mdOut:
                row.readFromMd(mdOut, objId)
                pcSet.append(rowToMode(row))

            pdb = AtomStruct(self._getPath("atoms.pdb"))
            self._defineOutputs(outputMean=pdb)

            pcSet.setPdb(pdb)
            self._defineOutputs(outputPCA=pcSet)

    # --------------------------- INFO functions --------------------------------------------
    def _summary(self):
        summary = []
        return summary

    def _validate(self):
        errors = []
        return errors

    def _citations(self):
        return ['harastani2022continuousflex']

    def _methods(self):
        pass

    # --------------------------- UTILS functions --------------------------------------------
    def _printWarnings(self, *lines):
        """ Print some warning lines to 'warnings.xmd',
        the function should be called inside the working dir."""
        fWarn = open("warnings.xmd", 'w')
        for l in lines:
            print >> fWarn, l
        fWarn.close()

    def getInputFiles(self):
        if self.pdbSource.get()==PDB_SOURCE_SUBTOMO:
            l= [f for f in glob.glob(self.pdbs.get()._getExtraPath('*.pdb'))]
        elif self.pdbSource.get()==PDB_SOURCE_PATTERN:
            l= [f for f in glob.glob(self.pdbs_file.get())]
        elif self.pdbSource.get()==PDB_SOURCE_OBJECT:
            l= [i.getFileName() for i in self.setOfPDBs.get()]
        elif self.pdbSource.get()==PDB_SOURCE_TRAJECT:
            l= [f for f in glob.glob(self.dcds_file.get())]
        elif self.pdbSource.get()==PDB_SOURCE_ALIGNED:
            l=[self.alignPdbProt.get()._getExtraPath("coords.dcd")]
        l.sort()
        return l

    def getPDBRef(self):
        if self.pdbSource.get()==PDB_SOURCE_TRAJECT:
            return self.dcd_ref_pdb.get().getFileName()
        elif self.pdbSource.get()==PDB_SOURCE_ALIGNED:
            return self.alignPdbProt.get()._getExtraPath("reference.pdb")
        else:
            return self.getInputFiles()[0]

    def getOutputMatrixFile(self):
        return self._getExtraPath('output_matrix.txt')

    def writePrincipalComponents(self, prefix, matrix):
        for i in range(self.reducedDim.get()):
            with open("%s/vec.%i"%(prefix,i+1), "w") as f:
                    for j in range(matrix.shape[1]):
                        f.write(" %e   %e   %e\n" % (matrix[i,j, 0], matrix[i,j, 1], matrix[i,j, 2]))
