# **************************************************************************
# * Authors: Rémi Vuillemot             (remi.vuillemot@upmc.fr)
# *
# * IMPMC, UPMC Sorbonne University
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# **************************************************************************

import multiprocessing
from pyworkflow.protocol.params import PointerParam, FileParam, USE_GPU, GPU_LIST, BooleanParam, StringParam,LEVEL_ADVANCED
from pwem.protocols import BatchProtocol
from pwem.objects import SetOfClasses2D
from xmipp3.convert import writeSetOfParticles, writeSetOfVolumes, readSetOfVolumes
from pyworkflow.utils import runCommand
from pwem.emlib.image import ImageHandler
import pwem.emlib.metadata as md
import os

class FlexBatchProtClusterSet(BatchProtocol):
    """
    Creates a collection of representative 3D volumes from a set of particle or volume clusters.
    The protocol is intended to generate structural representatives for previously identified
    classes, allowing each cluster to be visualized, compared, and interpreted as an independent
    conformational or structural state.

    AI Generated:

    Cluster Set Reconstruction (FlexBatchProtClusterSet) - User Manual
        Overview

        The Cluster Set Reconstruction protocol generates representative 3D volumes from a collection
        of previously defined classes. Its primary objective is to transform clustered experimental
        data into interpretable structural representations that can be used for visualization,
        comparison, classification, and downstream structural analysis.

        In cryo-EM and structural heterogeneity studies, clustering is frequently used to separate
        particles, volumes, or molecular conformations into groups that share similar characteristics.
        Once these groups have been identified, researchers often require a representative volume for
        each cluster in order to understand the structural meaning of the classification. This
        protocol provides that transition from abstract classes to biologically interpretable
        structures.

        Inputs and Biological Context

        The protocol operates on a set of classes generated by previous classification or clustering
        procedures. Each class is assumed to represent a population of observations sharing common
        structural features. Depending on the workflow, these observations may correspond to particle
        images, reconstructed volumes, or structures derived from conformational analysis.

        From a biological perspective, clusters frequently correspond to distinct conformational
        states, structural intermediates, assembly configurations, or functional substates of a
        macromolecular complex. Generating representative volumes allows researchers to examine these
        populations individually and assess the biological relevance of the observed variability.

        Reconstruction of Class Representatives

        For classes derived from particle images, the protocol generates a three-dimensional
        representative volume for each cluster. The resulting structures summarize the information
        contained within all members of the class and provide a direct structural interpretation of
        the clustered population.

        When the input already consists of volumetric information, the protocol produces a
        representative volume that reflects the average characteristics of the structures assigned to
        the corresponding class. This enables consistent treatment of heterogeneous datasets that may
        originate from different stages of a structural analysis workflow.

        Computational Execution

        The protocol can take advantage of modern computational resources to accelerate processing.
        Depending on the available hardware, reconstruction may be performed using either CPU-based or
        GPU-accelerated execution. This flexibility allows the protocol to scale from small
        exploratory studies to large classification projects involving substantial numbers of classes.

        For biological users, the computational strategy generally does not alter the scientific
        interpretation of the results. Instead, it affects execution speed and resource utilization,
        making it possible to process large datasets more efficiently.

        Outputs and Interpretation

        The primary output is a set of representative 3D volumes, one for each input class. Each
        output volume can be examined independently to identify structural characteristics associated
        with the corresponding population.

        These reconstructed representatives are particularly useful for studying conformational
        landscapes, identifying dominant structural states, evaluating classification quality, and
        exploring transitions between biological states. Differences observed between cluster
        representatives may reveal meaningful molecular motions, assembly changes, or functional
        rearrangements.

        Practical Recommendations

        Before interpreting the resulting volumes, it is advisable to verify that the underlying
        classification accurately separates biologically meaningful populations. Poorly defined
        clusters may produce representative structures that appear noisy, ambiguous, or difficult to
        interpret.

        When multiple representatives exhibit subtle differences, side-by-side visualization and
        quantitative comparison can help determine whether the observed variability reflects genuine
        biological heterogeneity or residual classification uncertainty. The protocol is most valuable
        when used as part of a broader workflow aimed at understanding structural variability within a
        molecular system.

        Final Perspective

        Cluster representatives provide an essential bridge between classification results and
        biological interpretation. By transforming groups of related observations into representative
        three-dimensional structures, the protocol enables researchers to visualize, compare, and
        understand the structural diversity present within complex cryo-EM datasets. The resulting
        volumes serve as a foundation for studying conformational variability, functional mechanisms,
        and the organization of heterogeneous molecular populations.
    """
    _label = 'cluster set'

    def _defineParams(self, form):
        form.addHidden('inputSet', PointerParam, pointerClass='SetOfParticles,SetOfVolumes')
        form.addHidden('inputClasses', PointerParam, pointerClass='SetOfClasses2D,SetOfClasses3D')
        form.addHidden('inputPDBs', PointerParam, pointerClass='SetOfAtomStructs')
        form.addHidden(USE_GPU, BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation.\
                       Select the one you want to use.")

        form.addHidden(GPU_LIST, StringParam, default='0',
                       expertLevel=LEVEL_ADVANCED,
                       label="Choose GPU IDs",
                       help="Add a list of GPU devices that can be used")
        form.addParallelSection(threads=4, mpi=1)

    # --------------------------- INSERT steps functions --------------------------------------------

    def _insertAllSteps(self):
        self._insertFunctionStep('convertInputStep')
        self._insertFunctionStep('reconstructStep')
        self._insertFunctionStep('createOutputStep')

    # --------------------------- STEPS functions --------------------------------------------

    def convertInputStep(self):
        pass

    def reconstructStep(self):
        inputClasses = self.inputClasses.get()

        for i in inputClasses:
            if i.getObjId() != 0:
                classFile = self._getExtraPath("class%s.xmd" % str(i.getObjId()).zfill(6))
                if isinstance(inputClasses, SetOfClasses2D):
                    writeSetOfParticles(i, classFile)
                else:
                    writeSetOfVolumes(i,classFile)

        for i in inputClasses:
            if i.getObjId() != 0:
                classFile = self._getExtraPath("class%s.xmd" % str(i.getObjId()).zfill(6))
                classVol = self._getExtraPath("class%s.vol" % str(i.getObjId()).zfill(6))
                if isinstance(inputClasses, SetOfClasses2D):
                    args = "-i %s -o %s " % (classFile, classVol)
                    args += ' --sampling %f' % self.inputClasses.get().getSamplingRate()

                    if self.useGpu.get():
                        args += ' --thr %d' % self.numberOfThreads.get()

                    if self.useGpu.get():
                        if self.numberOfMpi.get() > 1:
                            self.runJob('xmipp_cuda_reconstruct_fourier', args,
                                        numberOfMpi=len((self.gpuList.get()).split(',')) + 1)
                        else:
                            self.runJob('xmipp_cuda_reconstruct_fourier', args)
                    else:
                        if self.numberOfMpi.get() > 1 :
                            progname = "xmipp_mpi_reconstruct_fourier "
                            self.runJob(progname, args)
                        else:
                            progname = "xmipp_reconstruct_fourier "
                            runCommand(progname + args)
                else:
                    classAvg = ImageHandler().computeAverage(i)
                    classAvg.write(classVol)

    def createOutputStep(self):
        outputMd = md.MetaData()
        inputClasses = self.inputClasses.get()
        for i in inputClasses:
            if i.getObjId() != 0:
                classVol = self._getExtraPath("class%s.vol" % str(i.getObjId()).zfill(6))
                index = outputMd.addObject()
                outputMd.setValue(md.MDL_IMAGE, classVol, index)
                outputMd.setValue(md.MDL_ITEM_ID, i.getObjId(), index)
        outputMd.write(self._getExtraPath("outputVols.xmd"))
        outputVols = self._createSetOfVolumes()
        readSetOfVolumes(self._getExtraPath("outputVols.xmd"),outputVols)
        outputVols.setSamplingRate(inputClasses.getSamplingRate())
        self._defineOutputs(outputVols=outputVols)
    # --------------------------- INFO functions --------------------------------------------
    def _summary(self):
        summary = []
        return summary

    def _validate(self):
        errors = []
        return errors

    def _citations(self):
        return ['harastani2022continuousflex']

    def _methods(self):
        return []
