# **************************************************************************
# * Authors:    Mohamad Harastani            (mohamad.harastani@igbmc.fr)
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

from pyworkflow.protocol.params import PointerParam, FileParam
from pwem.protocols import BatchProtocol
from pwem.objects import Volume, SetOfVolumes
from xmipp3.convert import writeSetOfVolumes
import pwem.emlib.metadata as md
import os
from pwem.utils import runProgram


class FlexBatchProtTomoFlowCluster(BatchProtocol):
    """
    Creates a representative volume from a cluster of tomographic structures obtained after
    dimensionality reduction analysis. The protocol gathers all volumes belonging to a selected
    cluster and generates a consensus structural representation that summarizes the common features
    present within that population.

    AI Generated:

    TomoFlow Cluster Volume (FlexBatchProtTomoFlowCluster) - User Manual
        Overview

        The TomoFlow Cluster Volume protocol is designed to characterize a cluster of related
        structures identified during TomoFlow dimensionality reduction analyses. Its main purpose
        is to transform a collection of clustered volumes into a biologically meaningful consensus
        representation that can be inspected, interpreted, and compared with other structural
        states.

        In studies of structural heterogeneity, clustering is commonly used to separate volumes
        into groups that represent similar conformations, functional states, or trajectories
        within a continuous landscape. Once a cluster has been identified, researchers often need
        a representative structure that captures the average properties of that population. This
        protocol provides that summary representation.

        Inputs and General Workflow

        The protocol operates on a previously defined cluster generated from a TomoFlow
        dimensionality reduction workflow. The selected cluster contains a subset of volumes that
        share similar structural characteristics according to their position in the reduced
        conformational space.

        During execution, all volumes associated with the cluster are gathered into a dedicated
        dataset while preserving the experimental information required for downstream analysis.
        The protocol then combines the structural information from every member of the cluster to
        generate a representative average volume.

        Biological Interpretation of Clusters

        Clusters often correspond to regions of the conformational landscape that contain related
        molecular states. Depending on the biological system, a cluster may represent a stable
        conformation, an intermediate state, or a family of structures sharing similar global
        organization.

        The representative volume generated by this protocol provides an intuitive way to inspect
        the dominant structural features present within the cluster. Regions that are consistently
        observed across the population tend to be reinforced in the average, whereas highly
        variable regions may appear less defined.

        Averaging and Structural Heterogeneity

        Averaging is useful because it reduces random noise and enhances reproducible structural
        information. For clusters that contain relatively homogeneous structures, the resulting
        volume often provides a clear description of the underlying molecular state.

        When a cluster contains substantial variability, however, averaging should be interpreted
        carefully. Flexible domains, transient interactions, or continuous motions may become
        blurred in the final representation. In such cases, the average volume should be viewed as
        a summary of the cluster rather than an exact depiction of any individual structure.

        Outputs and Their Interpretation

        The main output is a representative volume corresponding to the average of all volumes
        belonging to the selected cluster. This volume can be visualized directly, compared with
        averages from other clusters, or used as input for additional structural analyses.

        Because the output preserves the sampling information associated with the original data,
        it can be integrated into downstream cryo-EM and cryo-electron tomography workflows
        without requiring additional preparation.

        Practical Recommendations

        The biological value of the resulting average depends strongly on the quality of the
        clustering stage. Clusters that represent coherent structural populations generally
        produce informative averages that facilitate interpretation and visualization.

        Researchers are encouraged to compare representative volumes from multiple clusters to
        identify conformational transitions, alternative structural states, or distinct functional
        substates. Visual inspection of cluster members can also help determine whether the
        resulting average accurately reflects the underlying population.

        Final Perspective

        For studies focused on continuous heterogeneity and structural landscapes, cluster-based
        representative volumes provide an effective bridge between large collections of individual
        structures and biologically interpretable models. By summarizing the common characteristics
        of a selected cluster, this protocol helps transform complex conformational information
        into forms that are easier to analyze, compare, and communicate.
    """
    _label = 'tomoflow vol cluster'

    def _defineParams(self, form):
        form.addHidden('inputHeteroFlowDimred', PointerParam, pointerClass='EMObject')
        form.addHidden('sqliteFile', FileParam)

    #--------------------------- INSERT steps functions --------------------------------------------

    def _insertAllSteps(self):
        volumesMd = self._getExtraPath('volumes.xmd')
        outputVol = self._getExtraPath('average.spi')

        self._insertFunctionStep('convertInputStep', volumesMd)
        self._insertFunctionStep('averagingStep')
        self._insertFunctionStep('createOutputStep', outputVol)

    #--------------------------- STEPS functions --------------------------------------------

    def convertInputStep(self, volumesMd):
        # It is unusual to create the output in the convertInputStep,
        # but just to avoid reading twice the sqlite with particles
        # inputSet = self.inputHeteroFlowDimred.get().getInputParticles().get()
        inputSet = self.inputHeteroFlowDimred.get().getInputParticles()
        partSet = self._createSetOfVolumes()
        # partSet = SetOfVolumes()
        partSet.copyInfo(inputSet)
        tmpSet = SetOfVolumes(filename=self.sqliteFile.get())
        partSet.appendFromImages(tmpSet)
        # Register outputs
        partSet.setAlignmentProj()

        self._defineOutputs(OutputVolumes=partSet)
        # self._defineTransformRelation(inputSet, partSet)
        writeSetOfVolumes(partSet, volumesMd)


    def averagingStep(self):
        volumesMd = self._getExtraPath('volumes.xmd')
        mdVols = md.MetaData(volumesMd)
        counter = 0
        for objId in mdVols:
            counter = counter + 1
            imgPath = mdVols.getValue(md.MDL_IMAGE, objId)
            outputVol = self._getExtraPath('average.spi')
            tempVol = self._getExtraPath('temp.spi')
            extra = self._getExtraPath()

            params = '-i %(imgPath)s -o %(tempVol)s --type vol ' % locals()
            runProgram('xmipp_image_convert',params)

            if counter == 1 :
                os.system("mv %(tempVol)s %(outputVol)s" % locals())

            else:
                params = '-i %(tempVol)s --plus %(outputVol)s -o %(outputVol)s ' % locals()
                runProgram('xmipp_image_operate', params)

        params = '-i %(outputVol)s --divide %(counter)s -o %(outputVol)s ' % locals()
        runProgram('xmipp_image_operate', params)
        os.system("rm -f %(tempVol)s" % locals())


    def createOutputStep(self, outputVol):
        vol = Volume()
        vol.setFileName(outputVol)
        vol.setSamplingRate(self.OutputVolumes.getSamplingRate())
        self._defineOutputs(outputVol=vol)

    #--------------------------- INFO functions --------------------------------------------
    def _summary(self):
        summary = []
        return summary

    def _validate(self):
        errors = []
        return errors

    def _citations(self):
        return ['harastani2022continuousflex']

    def _methods(self):
        return []

